### ISSUE TITLE
Movie trailers

### ISSUE THREAD

**Issue by bbackspace** [tanmayrajani/cinephi1e#2]
Possible tags:
# sneakpeek
# trailer

Can use Google search or YouTube search API for getting the trailer link?

**Comment by beingadityak** [comment]
Suggested package: [youtube-search](https://www.npmjs.com/package/youtube-search)

**Comment by beingadityak** [comment]
I've started working on this module @tanmayrajani @bbackspace

**Comment by beingadityak** [comment]
Please check the latest pull request to 'dev1' branch. #10

**Comment by tanmayrajani** [comment]
Good work bro, @beingadityak 

Apart from having tag #trailer, I am also considering this to be a part of #meta instead. What are your thoughts? @bbackspace

**Comment by beingadityak** [comment]
I am also thinking, how about adding the tags as a part of the persistent menu?

**Comment by tanmayrajani** [comment]
@beingadityak How would user add the movie name in that case? I don't think that would work. Even if it does, it wouldn't look neat AFAIK

**Comment by beingadityak** [comment]
Added the trailers to `#meta`. Please review PR #11

**Comment by tanmayrajani** [comment]
Trailer added as button ("Watch Trailer") and part of `#meta` as discussed. Added a9635d0 to fix few issues. 

Thanks @beingadityak for the PR. :vulcan_salute: 

Closing this issue.
